name: Yocto Release
on:
  push:
    # branches:
    #   - main
    # paths:
    #   - conf/distro/HULKs-OS.conf
jobs:
  release:
    name: Release
    runs-on:
      - ubuntu-latest
    #   - self-hosted
    #   - yocto-v1
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yocto_release
