name: Yocto Release
on:
  push:
    # branches:
    #   - main
    # paths:
    #   - conf/distro/HULKs-OS.conf
jobs:
  release:
    name: Release
    runs-on:
      # - ubuntu-latest
      - self-hosted
    container:
      image: yocto_release
      volumes:
        - yocto_release_build:/yocto/build
    steps:
      - uses: actions/checkout@v3
      - run: cd .github/actions/yocto_release/ && npm ci
      - uses: ./.github/actions/yocto_release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
