name: Yocto Release
on: push
jobs:
  cicd:
    name: Yocto Continuous Integration and Delivery
    runs-on:
      - self-hosted
    container:
      image: ghcr.io/hulks/yocto_release
      options: --user=1000:1000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: meta-hulks
      - name: Checkout Yocto layers
        run: kas checkout meta-hulks/kas-project.yml
      - name: Test
        run: cd meta-hulks && git describe --tags --abbrev=0
      # - name: Install dependencies
      #   run: cd meta-hulks/.github/actions/yocto_release/ && npm ci
      # - name: Build and release
      #   uses: ./meta-hulks/.github/actions/yocto_release
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
