name: Yocto Release
on:
  push:
    # branches:
    #   - main
    # paths:
    #   - conf/distro/HULKs-OS.conf
jobs:
  release:
    name: Yocto Release
    runs-on:
      # - ubuntu-latest
      - self-hosted
    container:
      image: ghcr.io/hulks/yocto_release
      options: --user=1000:1000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: meta-hulks
      - name: Install Dependencies
        run: cd meta-hulks/.github/actions/yocto_release/ && npm ci
      - name: Build and Release
        uses: ./meta-hulks/.github/actions/yocto_release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
